### PR TITLE
adding the role that can be assumed during integration test

### PR DESCRIPTION
**Pull request by esc**
Review requested

### CODE REVIEW

**Comment by esc** [comment]
@sdomme can you check this out please? I am not sure if `AWS: Ref:`` works via cfn-sphere.

**Comment by sdomme** [comment]
I'm currently testing it out. The disadvantage is, user have to remove the extra role configuration, if they did not use the integration test. Otherwise they get a dummy role (maybe a security issue).

@esc Could it be a better idea to have a separate template which supports integration test environment?

**Comment by esc** [comment]
Sounds good.

On 23 November 2015 10:46:27 CET, Sergej Domme notifications@github.com wrote:

> I'm currently testing it out. The disadvantage is, user have to remove
> the extra role configuration, if they did not use the integration test.
> Otherwise they get a dummy role (maybe a security issue).
> 
> @esc Could it be a better idea to have a separate template which
> supports integration test environment?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ImmobilienScout24/crassus/pull/4#issuecomment-158889607

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdomme** [comment]
I fixed the integration-test template, so it works with cfn-sphere now.
Also I split the template and configuration in a default and integration-test version, so user can decide which one to use to fit their requirements. (We need to deploy the integration-test one)
@esc review for review required :-)

**Pull request merged**
